### ISSUE TITLE
Refactor codebase

### ISSUE THREAD

**Issue by capjamesg** [capjamesg/indieweb-utils#11]
The IndieWeb utils library is presently stored at `src/indieweb_utils.py`. During development, one file was sufficient to maintain all of the code in the project. Now that more functions have been added (with intent to add more) it is a good idea to evaluate how we can split up the codebase into multiple files. This will need to be carefully considered as we don't want to break any existing functions.

**Comment by jamesvandyne** [comment]
@capjamesg I can take this issue and split it up into modules. I think we should make a sub-package for each "group" of functionality. i.e. 

indieweb_utils.webmentions
indieweb_utils.indieauth

And so forth. Does that sound reasonable to you? We should be able to keep compatibility as well.

**Comment by jamesvandyne** [comment]
The codebase could be further refactored, but it's not enough to have a big ticket for it. The major refactor (splitting it sub-packages) was handled with #12, so I'll close this issue.
