### ISSUE TITLE
Generate Usage and Type Documentation from Docstrings

### ISSUE THREAD

**Issue by jamesvandyne** [capjamesg/indieweb-utils#16]
It would be helpful if we could automatically generate parts of the documentation directly from the library's source code. This would help us make sure that our code and documentation says in sync, as well as encourage us to write good docstrings. In theory it should also be able to generate return type / input docs as well, once we have typehints everywhere.

I've seen projects that do it before so I know it's possible.

TODO:

* Investigate the proper sphinx settings required to auto-generate the docs
* Set base sphinx documentation settings

**Comment by capjamesg** [comment]
@jamesvandyne I am working on this in a new PR. Should we include code snippets in our docstrings so that working examples show up on our documentation, too? Or should we defer such examples to the actual rst markdown files in which the library is documented?

**Comment by jamesvandyne** [comment]
@capjamesg Include it in the doc strings, I reckon. That way if we do change something, the example is right there too.

**Comment by capjamesg** [comment]
We have now have Sphinx installed and configured. We also have complete docstrings for almost all functions in the library. Thus, I am going to mark this issue as closed.
