### ISSUE TITLE
Reply context should return a jf2 object

### ISSUE THREAD

**Issue by capjamesg** [capjamesg/indieweb-utils#2]
The reply context function (`get_reply_context()`) should return a jf2 object rather than the arbitrary JSON object the function currently returns. jf2 follows a standard and is easier to work with than the current object.

**Comment by jamesvandyne** [comment]
Searching around, jf2 seems to be JSON (micro)formats2 from described in [this post](https://randomgeekery.org/post/2020/11/using-the-webmentionio-api/) by Brian, right? Are you envisioning this would return a dictionary?

One of the hardest parts, at least in my experience, in working with IndieWeb related things is dealing with having everything being dictionaries on the backend.

What do you think about making indieweb-utils return proper objects or data-classes as a general way of working? There's a number of benefits:

* Avoid key name strings when accessing the values, which is easy to flub. 
* Allow us to type the data, which would allow developers to catch bugs quicker (before it gets merged).
* Autocomplete from IDEs works.
* Makes it immediately clear what the possible key values are.
* We can also use it as an opportunity to interpret the data e.g. converting a datetime into a Python datetime object etc...

I've used them for replies in Tanzawa's indieweb support and it works well. 

https://github.com/jamesvandyne/tanzawa/blob/main/apps/indieweb/application/extract.py#L10

The main challenge would be needing to decide on a way to normalize properties with a "-" in them e.g. `repost-of`. In Tanzawa I convert it to the python standard `repost_of`. The only downside is that we could only type common / known / regular properties. However, we could always add an `extra_properties: Dict[str, Any]` property to store extra values?

**Comment by capjamesg** [comment]
@jamesvandyne Thank you for your comment!

I like the idea of returning proper objects. This seems like a more Pythonic approach to returning data versus a dictionary. Also, dictionaries are harder to document.

I propose the best place to start is with the [get_reply_context() function](https://github.com/capjamesg/indieweb-utils/blob/main/src/indieweb_utils.py#L511). That function returns a "h_entry" dictionary at the moment.

Since the library is in its early stages, making these changes now would set a solid foundation without creating too many breaking changes further down the line.

I think normalising properties with an underscore is appropriate. I have taken that approach throughout the library as it preserves the readability of values. The extra_properties dictionary idea seems appropriate if extra values are ever needed.

**Comment by capjamesg** [comment]
@jamesvandyne Since the introduction of objects as the method of data representation would likely introduce breaking changes, it seems prudent to make this a change for v1.0.0 as opposed to a minor version bump. This would ensure the library follows semantic versioning practices. What do you think?

**Comment by jamesvandyne** [comment]
@capjamesg Yes - it would be breaking changes. I think it depends on how we define "1.0" and when we're planning on hitting that. I feel like we're a ways off from a 1.0.0. Current version is 0.1.2, so if we were to change the return type, upgrading it to 0.2.0 with a change log / upgrade notes should be sufficient.

Also, we can dataclass' [asdict](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict) method to allow us to use dataclasses internally and return a dictionary, until we're ready to make a release with breaking changes.

**Comment by capjamesg** [comment]
@jamesvandyne Since this issue was created, we have migrated the reply context to return an object rather than a jf2 dictionary, per our move to objects over dictionaries where possible. Can I close this issue?

**Comment by jamesvandyne** [comment]
Yep - good point. Closing as it's been handled.
