### ISSUE TITLE
Proposal to introduce IndieAuth server-side authentication logic

### ISSUE THREAD

**Issue by capjamesg** [capjamesg/indieweb-utils#27]
I was recently thinking that we could introduce IndieAuth server-side logic into the IndieWeb Utils library. This would cover:

- Authorization endpoint token verification
- Token endpoint verification
- Potentially token generation
- h-x-app verification (although this is not widely supported so may be worth discussing separately).

This logic would make it easy for anyone to set up their own IndieAuth endpoints in their Python applications. For instance, a developer could use the methods above to build an IndieAuth endpoint into a blogging client or a Microsub server or a publishing tool.

The logic would be implemented in functions rather than wrappers to allow for modular building, critical since authentication flows can differ and still be in line with the spec.

I have already written most of the code needed for this change but it shall need refactoring to work. I can take this on. Before I do, I'd love to facilitate feedback on implementation of this.

cc @jamesvandyne @angelogladding.

**Comment by jamesvandyne** [comment]
@capjamesg Yes! I would love this and it's quite timely for my own needs with Tanzawa (I realized it works for services like ownyourswarm, but not for the main IndieWeb wiki...) I've been reading the spec confusing myself while trying to modify it, so this would be a great help.
