### ISSUE TITLE
Planning the next release

### ISSUE THREAD

**Issue by capjamesg** [capjamesg/indieweb-utils#30]
Since v0.1.3, we have introduced a number of new features to the library. We have also introduced some breaking changes that relates to the return types sent by functions. This has been part of our move to a more Pythonic typeclass-based approach versus returning aribitrary dictionaries (which impose a burden of validation on those using the package).

We should discuss:

1. What changes need to be made to release the next version of the library. 
2. What new features, if any, we would like to make part of the next release.
3. What identifier the release could be assigned given the breaking changes introduced above. Our next big release could potentially be v0.2.0. 
4. How we document our changes from version to version. We do not have a detailed changelog just yet. This seems like a prudent time to start one.

**Comment by capjamesg** [comment]
@jamesvandyne Once we modify the test cases for the features that use network requests instead of referencing local files and objects, should we release what we have? I am excited to release the latest version and to start using it in my own projects.

**Comment by jamesvandyne** [comment]
@capjamesg Sorry for the delay. I agree, once the tests aren't using the network, we can make a new release. We've added heaps of new capabilities, so 0.2.0 seems fitting. Agree, it is the right time to start a proper CHANGELOG file. We can write it manually for now.

In the future we may want to introduce [towncrier](https://pypi.org/project/towncrier/) into the project to help build our changelog The way towncrier works is each branch adds a "news" file with a summary of changes to a changelog directory with a name like `123.bugfix.rst`. When towncrier is run it will read all of the news files, sort them by category (bugfix, feature etc..), and prepend them to the CHANGELOG file.

**Comment by capjamesg** [comment]
Since we have launched v0.2.0, I am going to close this issue.
