### ISSUE TITLE
Introduce black formatter to build process

### ISSUE THREAD

**Issue by capjamesg** [capjamesg/indieweb-utils#32]
Should we start using the [black](https://github.com/psf/black) formatter to keep our code compliant with PEP 8? Black automatically makes changes to code, thus saving us time from manually responding to linting errors raised when running the full `tox` command. Black is used by many open-source libraries and may be worth considering for indieweb-utils, too.

**Comment by jamesvandyne** [comment]
It's already introduced (and documented in the README). If you run `tox -e fmt` it will automatically run black / isort and fix all errors for you. I need to look how to configure it on my personal computer, but I've got it setup on my work computer to automatically run black/isort when I edit any python files, so I always commit black/isorted code.

**Comment by capjamesg** [comment]
Thank you! I didn't notice this had been done until I cleaned up all the liniting issues. Then, I noticed that black was included in the tox output. I shall close this issue.
