### ISSUE TITLE
Proposal to add feed parsing logic for JSON Feed, h-feed, Atom, and RSS

### ISSUE THREAD

**Issue by capjamesg** [capjamesg/indieweb-utils#37]
Microsub servers deal with data in jf2 objects. This means a server must translate data from any types of feeds it wishes to support into jf2. I have written code that parses JSON Feed, h-feed, and XML feeds (although Atom and RSS do need to be disambiguated) for my Microsub server and wonder whether this would be a useful addition to the library.

This functionality would take a feed, identify its type, and then return one object with relevant values (title, images, media, etc). This object could then be translated into jf2, either in a separate library function or we could leave this translation up to implementors. Such a feature would avoid one needing to write parsing code for four different standards to build a Microsub server (or for any other type of feed reader). The feed parsing logic would rely on existing libraries (feedparser, mf2py, etc.), this feature would only act as a translation layer.

The downside of this approach is that it might create less rich features than are available in individual feeds. Thus, a necessary caveat would be to restrict this change to only properties that relate to jf2.

**Comment by kevinmarks** [comment]
would adding jsonfeed and h-feed to feedparser make more sense?

**Comment by capjamesg** [comment]
@kevinmarks That is a good point. Perhaps that would be more appropriate since this library doesn't have any particular focus on feed parsing, unlike [feedparser](https://github.com/kurtmckee/feedparser).

**Comment by capjamesg** [comment]
I am going to mark this issue as closed for now, although we could revisit this topic in the future if there is demand from users of the library.
