### ISSUE TITLE
Transition license to CC0

### ISSUE THREAD

**Issue by capjamesg** [capjamesg/indieweb-utils#73]
indieweb-utils aims to make developers who are building IndieWeb applications more efficient. Some of our code may be useful in contexts greater than what we have in mind as we design this library, and I wanted to raise the issue as to whether we can transition the library from MIT to CC0 (or an equivalent OSI-approved license).

Under CC0, code that uses parts of indieweb-utils could be copied without having to cite our original license. This is useful for developers who may want to adapt the code we write to specific applications without necessarily using MIT. CC0 also does not require explicit attribution, so developers can adapt our code to their needs without citing indieweb-utils'.

For more information on CC0, see these resources:

https://creativecommons.org/share-your-work/public-domain/cc0/
https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F

To make this transition, we first need to agree:

1. CC0 is the right option.
2. If CC0 is the right option, all copyright holders must provide consent for a transition. This is, at present, myself, @jamesvandyne, @tantek (IIRC), and @angelogladding.
3. If CC0 is deemed not to be the right option, we should agree on next steps in this thread.

**Comment by angelogladding** [comment]
"First of all, speculation that we did not anticipate CC0 usage for software at the time is true."
https://web.archive.org/web/20150906005825/https://lists.opensource.org/pipermail/license-review/2012-February/000231.html

Both of the following are OSI approved public-domain-equivalent licenses:
- https://en.wikipedia.org/wiki/MIT_License#MIT_No_Attribution_License
- https://en.wikipedia.org/wiki/BSD_licenses#0-clause

We should probably use one of the latter two. Both are on the SPDX license list used by Python Poetry: https://spdx.org/licenses/

Additionally, we could multi-license the code and documentation. eg. https://symfony.com/license

MIT-0 appears to be more widely supported than 0BSD at the time.

**Comment by capjamesg** [comment]
Thank you for the information @angelogladding. I am in support of MIT-0 for the codebase in this software. I didn't think about the documentation. Do you have any preference on a license for documentation (CC Share-Alike, etc.)? I'll do more research into this.

**Comment by jamesvandyne** [comment]
I don't have any strong opinions. As long as users can use the library/code in their projects easily, I'm satisfied. MIT No Attribution seems reasonable. I think for documentation, a permissive CC license should be sufficient.

**Comment by capjamesg** [comment]
After further discussion with @angelogladding in the IndieWeb chat, my support is leaning toward 0 BSD.

In terms of documentation, I like [CC0 Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/) but I am open to other suggestions. What does everyone think?

**Comment by angelogladding** [comment]
For what it's worth I'll bless a license change of the code to `0BSD`.

I'm not sure there's any point in dual licensing under different public-domain-equivalents. It only complicates things. You might actually want to consider licensing the documentation `CC-BY` or even something more restrictive `CC-BY[-SA[-ND]]` depending on how you'd like to control the use of the documentation you are writing.

I believe the code should be freely copyable for reasons we've already discussed. I also believe your documentation efforts deserve attribution.
