### ISSUE TITLE
Add optional endpoint arg to send_webmention

### ISSUE THREAD

**Issue by snarfed** [capjamesg/indieweb-utils#85]
[From #indieweb-dev](https://chat.indieweb.org/dev/2022-10-21#t1666377226882600): you have the `discover_webmention_endpoint` function, but `send_webmention` doesn't currently accept an explicit endpoint. Maybe add one as an optional arg?

**Comment by capjamesg** [comment]
I have made this change in commit ffa9f86. I will make sure this change is included in an upcoming release.
